#!/usr/bin/env bash
# script that_narates story_of_passwd
# f1:USERNAM f2: PASSCODe f3:USERID f4:GROUpId f5:UIF f6:HOM f7:COMAND

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
    echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done < /etc/passwd
